all:
	make -C Snake
	make -C Qix
	make -C SolarFox
	make -C Bomberman
clean:
	make -C Snake clean
	make -C Qix clean
	make -C SolarFox clean
	make -C Bomberman clean
fclean:
	make -C Snake fclean
	make -C Qix fclean
	make -C SolarFox fclean
	make -C Bomberman

re: fclean all
