all:
	make -C NCurseInterface
	make -C SFMLInterface
	make -C CacaInterface
clean:
	make -C NCurseInterface clean
	make -C SFMLInterface clean
	make -C CacaInterface clean

fclean:
	make -C NCurseInterface fclean
	make -C SFMLInterface fclean
	make -C CacaInterface fclean

re: fclean all
